[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
solc-version = "0.8.27"
optimizer = true
optimizer_runs = 300
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["vault.sol"]
ffi = false
force = true
viaIR = true
fs_permissions = [{ access = "read-write", path = "./" }]

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

[invariant]
runs = 256
depth = 32
fail_on_revert = true

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
contract_new_lines = true
sort_imports = true
ignore=["./contracts/interfaces/IDiamondLoupe.sol", "./contracts/interfaces/IDiamondCut.sol","./test/*", "./script/*", "./contracts/libraries/*", "./contracts/Mocks/*", "./contracts/upgradeInitializers/*"]